name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Build and test (Maven)
        run: mvn -B -ntp -DskipTests=false verify

      - name: Build Docker image (no push)
        run: |
          docker build -t emotionalbook-api:ci .

